### ISSUE TITLE
Unable to import "AppDelegate.h" file in BTCardFormViewController class

### ISSUE THREAD

**Issue by incipio-srinu** [braintree/braintree-ios-drop-in#110]
### General information

* SDK/Library version: DropIn UI V6.2.0
* Environment: Sandbox
* iOS Version and Device: iPhone 7 plus, iOS 11.0
* Integration type: CocoaPods

### Issue description

I am unable to import AppDelegate.h file in BTCardFormViewController.h file. It is showing error as **"AppDelegate.h"** file not found. I am 100% sure I have file called AppDelegate.h. Thank you for your efforts

**Comment by crookedneighbor** [comment]
@incipio-srinu It's probably better to [contact our support team directly](https://articles.braintreepayments.com/forms/contact) to troubleshoot your integration, since this issue doesn't look like it's a problem with the SDK itself. 

I'm going to close this for now, but definitely contact our support team about this if you're still having issues.
