### ISSUE TITLE
Can i set the visibility of card false in brain tree drop-in?

### ISSUE THREAD

**Issue by khanrafay** [braintree/braintree-ios-drop-in#161]

**Comment by scannillo** [comment]
Hello. I am not sure what you are asking here. If you think there is an issue with one of our SDKs, feel free to open a new issue and fill out the Issue template with more details on your integration and the problem you face.

Otherwise, feel free to contact Braintree Support at
https://help.braintreepayments.com/ or 877.434.2894, where they can help you troubleshoot or answer questions related to using our SDKs.
