### ISSUE TITLE
Dropin 7.3.0 is not compatible with Braintree 4.27.0

### ISSUE THREAD

**Issue by pcki11** [braintree/braintree-ios-drop-in#172]
### General information

* SDK/Library version: 4.27.0
* Environment: any
* iOS Version and Device: building for iOS 8+
* Integration type and version: cocoapods 1.7.5

### Issue description
Having defined both in a podfile like this:
```
    pod 'Braintree', '4.27.0'
    pod 'BraintreeDropIn', '7.3.0'
```
Results in:
```
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Braintree/Core":
  In snapshot (Podfile.lock):
    Braintree/Core (= 4.27.0)

  In Podfile:
    Braintree (= 4.27.0) was resolved to 4.27.0, which depends on
      Braintree/Core (= 4.27.0)

    BraintreeDropIn (= 7.3.0) was resolved to 7.3.0, which depends on
      BraintreeDropIn/DropIn (= 7.3.0) was resolved to 7.3.0, which depends on
        Braintree/Core (~> 4.26.1)

Specs satisfying the `Braintree/Core (= 4.27.0), Braintree/Core (= 4.27.0), Braintree/Core (~> 4.26.1)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by sestevens** [comment]
Hi @pcki11, thanks for pointing this out! You're correct that `BraintreeDropIn` is using the previous version of `Braintree`. This will be updated in a future release.

You don't need to include `pod 'Braintree', '4.27.0'` if you're using BraintreeDropIn, since the drop in already includes Braintree as a dependency.

Also, BraintreeDropIn supports a minimum deployment target of **iOS 9**, which it looks like is the root of the issue. See this line from your error message: 

```
Specs satisfying the `Braintree/Core (= 4.27.0), Braintree/Core (= 4.27.0), Braintree/Core (~> 4.26.1)` dependency were found, but they required a higher minimum deployment target.
``` 

If you need to support iOS 8, you'll need to use the base Braintree SDK rather than BraintreeDropIn.

**Comment by sestevens** [comment]
Actually, I spoke too soon. Braintree 4.26.1 is the _minimum_ version compatible with BraintreeDropIn, but BraintreeDropIn will use a later version if it's available.

Still, you will need to update your minimum deployment target to iOS 9 if you want to use BraintreeDropIn.
