### ISSUE TITLE
A localizedDescription in the BTPaymentMethodNonce is not localized

### ISSUE THREAD

**Issue by andriy-appuchino** [braintree/braintree-ios-drop-in#188]
### General information

* SDK/Library version: 6.5.0
* Environment: Sandbox and Production
* iOS Version and Device: any iOS (on Android is the same problem)
* Integration type and version: CocoaPods 1.8.3

### Issue description

The DropIn itself is well localized. But we get a `BTDropInResult` with `fetch(forAuthorization:, handler:)` and it contains a `BTPaymentMethodNonce` with a `localizedDescription` parameter, and it is not localized, although it should.

We tried with `es` and `zh-CN` localizations, but there is a string like `ending in 11`.

**Comment by sestevens** [comment]
@andriy-appuchino You're correct, the `localizedDescription` property on `BTPaymentMethodNonce` does not return localized strings. The name of the property is definitely confusing.

If you'd like to display a localized description, you could cast the `BTPaymentMethodNonce` to a `BTCardNonce`, use the `lastTwo` property to get the last two digits of the card number, and then have your app handle the localization.

We'll look into renaming this property to avoid confusion in the future.

**Comment by sestevens** [comment]
Just an update - this field has been removed from `BTPaymentMethodNonce` in the [v5 beta](https://github.com/braintree/braintree_ios/releases/tag/5.0.0-beta1) of Braintree iOS. We're currently in the process of updating Braintree Drop-in to use version 5 of Braintree iOS, so this field will be removed from Drop-in as well.

Instead of using `localizedDescription`, you can use the following fields:
- Venmo: [`username`](https://github.com/braintree/braintree_ios/blob/404b3b1fbd2772a2e81f73c25f19bb5cb5c60649/Sources/BraintreeVenmo/Public/BraintreeVenmo/BTVenmoAccountNonce.h#L15) on `BTVenmoAccountNonce`
- PayPal: [`email`](https://github.com/braintree/braintree_ios/blob/404b3b1fbd2772a2e81f73c25f19bb5cb5c60649/Sources/BraintreePayPal/Public/BraintreePayPal/BTPayPalAccountNonce.h#L17) on `BTPayPalAccountNonce`
- Cards: [`lastTwo`](https://github.com/braintree/braintree_ios/blob/404b3b1fbd2772a2e81f73c25f19bb5cb5c60649/Sources/BraintreeCard/Public/BraintreeCard/BTCardNonce.h#L40) on `BTCardNonce`

**Comment by sestevens** [comment]
Hi @andriy-appuchino, we just released a beta version of the Drop-in SDK that fixes this issue: https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0-beta1. The `localizedDescription` property has been replaced with `paymentDescription` on `BTDropInResult`.

We recommend taking a look at our [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) if you want to check out this beta.

**Comment by sestevens** [comment]
We released [v9](https://github.com/braintree/braintree-ios-drop-in/releases/tag/9.0.0), which has the fix mentioned above. Again, we recommend looking at the [Migration Guide](https://github.com/braintree/braintree-ios-drop-in/blob/master/V9_MIGRATION.md) for steps to update.
