### ISSUE TITLE
The Apple Pay wasn't show up

### ISSUE THREAD

**Issue by lijianyu1985** [braintree/braintree-ios-drop-in#203]
### General information

* SDK/Library version: 7.5.0
* Environment: Dev
* iOS Version and Device: Simulator iPhone 11 Pro Max 13.1 
* Integration type and version:  CocoaPods 1.8.4

### Issue description
The Apple Pay wasn't show up, please review the attachment

**Comment by lijianyu1985** [comment]
Just see: Connection to remote alert view service failed, from the debug console

**Comment by scannillo** [comment]
Which version of Xcode are you on? When developing, we experienced [an Xcode bug ](https://stackoverflow.com/questions/58563489/ios-applepay-pkpaymentauthorizationviewcontroller-not-appearing-in-xcode11-ios-1)where the iOS 13 simulators wouldn't present the Apple Pay sheet. It did work fine however in other iOS versions, and presented fine on a device.

**Comment by lijianyu1985** [comment]
Xcode Version: 11.3(11C29)

**Comment by lijianyu1985** [comment]
> Which version of Xcode are you on? When developing, we experienced [an Xcode bug ](https://stackoverflow.com/questions/58563489/ios-applepay-pkpaymentauthorizationviewcontroller-not-appearing-in-xcode11-ios-1)where the iOS 13 simulators wouldn't present the Apple Pay sheet. It did work fine however in other iOS versions, and presented fine on a device.

Xcode Version 11.3(11C29)

**Comment by scannillo** [comment]
Does the Apple Pay sheet present fine in other non iOS 13 simulators?

**Comment by lijianyu1985** [comment]
> Does the Apple Pay sheet present fine in other non iOS 13 simulators?

IOS 13.2.2 & 12.0 simulators are fine, I didn't verify other simulators.

**Comment by scannillo** [comment]
This is a known Xcode bug.

Here are a two references to other [confirmations](https://forums.developer.apple.com/thread/122629) of this [bug](https://stackoverflow.com/questions/58563489/ios-applepay-pkpaymentauthorizationviewcontroller-not-appearing-in-xcode11-ios-1). 

You should confirm that things work fine on all devices. I am going to close this, because it isn't an issue with our SDK. However, if you need additional help you can still comment!
